-- Insertar datos en la tabla de equipos
INSERT INTO equipos (nombre, ciudad, año_fundacion) VALUES
('FC Barcelona', 'Barcelona', 1899),
('Real Madrid', 'Madrid', 1902),
('Manchester United', 'Manchester', 1878),
('Bayern Múnich', 'Múnich', 1900),
('Juventus', 'Turín', 1897),
('Liverpool', 'Liverpool', 1892),
('Paris Saint-Germain', 'París', 1970),
('Inter de Milán', 'Milán', 1908),
('AC Milan', 'Milán', 1899),
('Chelsea', 'Londres', 1905),
('Borussia Dortmund', 'Dortmund', 1909),
('Ajax', 'Ámsterdam', 1900),
('Benfica', 'Lisboa', 1904),
('Oporto', 'Oporto', 1893),
('Atlético de Madrid', 'Madrid', 1903),
('Sevilla', 'Sevilla', 1890),
('Arsenal', 'Londres', 1886),
('Manchester City', 'Manchester', 1880),
('Tottenham Hotspur', 'Londres', 1882),
('Roma', 'Roma', 1927),
('Napoli', 'Nápoles', 1926),
('Milan', 'Milán', 1899),
('Valencia', 'Valencia', 1919),
('Athletic Club', 'Bilbao', 1898),
('Celtic', 'Glasgow', 1887),
('Rangers', 'Glasgow', 1872),
('Borussia Mönchengladbach', 'Mönchengladbach', 1900),
('Bayer Leverkusen', 'Leverkusen', 1904),
('AS Roma', 'Roma', 1927),
('Lazio', 'Roma', 1900),
('Porto', 'Oporto', 1893),
('Benfica', 'Lisboa', 1904),
('Villarreal', 'Villarreal', 1923),
('Real Sociedad', 'San Sebastián', 1909),
('Real Betis', 'Sevilla', 1907),
('Everton', 'Liverpool', 1878),
('West Ham United', 'Londres', 1895),
('Newcastle United', 'Nuevacastle', 1892),
('Sunderland', 'Sunderland', 1879),
('Birmingham City', 'Birmingham', 1875),
('Aston Villa', 'Birmingham', 1874),
('Wolverhampton Wanderers', 'Wolverhampton', 1877),
('Southampton', 'Southampton', 1885),
('Leeds United', 'Leeds', 1919),
('Norwich City', 'Norwich', 1902),
('Burnley', 'Burnley', 1882),
('Sheffield United', 'Sheffield', 1889),
('Sheffield Wednesday', 'Sheffield', 1867),
('Cardiff City', 'Cardiff', 1899),
('Swansea City', 'Swansea', 1912),
('Cádiz CF', 'Cádiz', 1910),
('Real Valladolid', 'Valladolid', 1928),
('Getafe', 'Getafe', 1983),
('Granada', 'Granada', 1931),
('Almería', 'Almería', 1989),
('Levante UD', 'Valencia', 1909),
('Málaga', 'Málaga', 1904),
('Real Zaragoza', 'Zaragoza', 1932),
('Deportivo La Coruña', 'La Coruña', 1906),
('Osasuna', 'Pamplona', 1920),
('Espanyol', 'Barcelona', 1900),
('Girona', 'Girona', 1930),
('Alavés', 'Vitoria-Gasteiz', 1921),
('Eibar', 'Eibar', 1940),
('Real Sporting de Gijón', 'Gijón', 1905),
('Rayo Vallecano', 'Madrid', 1924),
('CD Tenerife', 'Santa Cruz de Tenerife', 1912),
('UD Las Palmas', 'Las Palmas', 1949),
('Real Oviedo', 'Oviedo', 1926),
('Cádiz', 'Cádiz', 1910),
('Tenerife', 'Santa Cruz de Tenerife', 1922),
('Huesca', 'Huesca', 1960),
('Elche', 'Elche', 1923),
('Real Mallorca', 'Palma de Mallorca', 1916);

-- Insertar datos en la tabla de jugadores
INSERT INTO jugadores (nombre, edad, posicion, equipo_id) VALUES
('Lionel Messi', 36, 'Delantero', 1),
('Cristiano Ronaldo', 39, 'Delantero', 2),
('Marcus Rashford', 26, 'Delantero', 3),
('Robert Lewandowski', 35, 'Delantero', 4),
('Paulo Dybala', 30, 'Delantero', 5),
('Mohamed Salah', 31, 'Delantero', 6),
('Kylian Mbappé', 25, 'Delantero', 7),
('Neymar Jr.', 31, 'Delantero', 7),
('Luka Modrić', 38, 'Centrocampista', 2),
('Kevin De Bruyne', 33, 'Centrocampista', 3),
('Gareth Bale', 34, 'Delantero', 2),
('Virgil van Dijk', 32, 'Defensa', 6),
('Sadio Mané', 32, 'Delantero', 4),
('Son Heung-min', 31, 'Delantero', 3),
('Zlatan Ibrahimović', 42, 'Delantero', 9),
('Marco Verratti', 31, 'Centrocampista', 7),
('Gerard Piqué', 36, 'Defensa', 1),
('Sergio Ramos', 38, 'Defensa', 2),
('Antoine Griezmann', 33, 'Delantero', 15),
('Harry Kane', 30, 'Delantero', 17),
('Lautaro Martínez', 26, 'Delantero', 8),
('Romelu Lukaku', 31, 'Delantero', 8),
('Kante N\'Golo', 33, 'Centrocampista', 10),
('Frenkie de Jong', 26, 'Centrocampista', 1),
('Bruno Fernandes', 29, 'Centrocampista', 3),
('Thiago Alcântara', 33, 'Centrocampista', 6),
('Ederson', 30, 'Portero', 3),
('Alisson Becker', 31, 'Portero', 6),
('Jan Oblak', 31, 'Portero', 15),
('Marc-André ter Stegen', 31, 'Portero', 1),
('Keylor Navas', 37, 'Portero', 7),
('Edouard Mendy', 31, 'Portero', 10),
('César Azpilicueta', 34, 'Defensa', 10),
('Andrew Robertson', 30, 'Defensa', 6),
('Trent Alexander-Arnold', 25, 'Defensa', 6),
('Ruben Dias', 26, 'Defensa', 3),
('Matthijs de Ligt', 24, 'Defensa', 4),
('Kalidou Koulibaly', 32, 'Defensa', 5),
('Achraf Hakimi', 25, 'Defensa', 7),
('Dani Carvajal', 32, 'Defensa', 2),
('Jordi Alba', 35, 'Defensa', 1),
('Kieran Trippier', 34, 'Defensa', 15),
('Nicolo Barella', 27, 'Centrocampista', 8),
('Federico Chiesa', 26, 'Delantero', 5),
('Dominik Szoboszlai', 23, 'Centrocampista', 10),
('Phil Foden', 24, 'Centrocampista', 3),
('Jack Grealish', 29, 'Delantero', 3),
('Bukayo Saka', 22, 'Delantero', 17),
('Gabriel Jesus', 27, 'Delantero', 17),
('Ousmane Dembélé', 27, 'Delantero', 1),
('Eden Hazard', 33, 'Delantero', 2),
('Raheem Sterling', 29, 'Delantero', 10),
('Youssef En-Nesyri', 26, 'Delantero', 15),
('Dani Olmo', 25, 'Delantero', 1),
('Mason Mount', 25, 'Centrocampista', 3),
('Yusuf Yazici', 26, 'Centrocampista', 5),
('Leon Goretzka', 29, 'Centrocampista', 4),
('Sergio Busquets', 35, 'Centrocampista', 1),
('Isco', 31, 'Centrocampista', 4),
('David Silva', 38, 'Centrocampista', 3),
('Ciro Immobile', 34, 'Delantero', 15),
('Gerard Moreno', 31, 'Delantero', 12),
('Paco Alcácer', 30, 'Delantero', 12),
('Marco Asensio', 28, 'Delantero', 2),
('Giovani Lo Celso', 28, 'Centrocampista', 3),
('Mauro Icardi', 31, 'Delantero', 7),
('Wilfried Zaha', 31, 'Delantero', 10),
('Kalvin Phillips', 28, 'Centrocampista', 17),
('Declan Rice', 25, 'Centrocampista', 17),
('Mateo Kovačić', 29, 'Centrocampista', 10),
('Saúl Ñíguez', 29, 'Centrocampista', 15),
('Andreas Christensen', 28, 'Defensa', 10),
('Sergio Reguilón', 27, 'Defensa', 17),
('Lucas Hernández', 28, 'Defensa', 4),
('Ben White', 26, 'Defensa', 17);


-- Insertar datos en la tabla de árbitros
INSERT INTO arbitros (nombre, nacionalidad, experiencia) VALUES
('Antonio Mateu Lahoz', 'España', 16),
('Daniele Orsato', 'Italia', 15),
('Björn Kuipers', 'Países Bajos', 20),
('Clement Turpin', 'Francia', 10),
('Mark Clattenburg', 'Inglaterra', 18),
('Felix Zwayer', 'Alemania', 15),
('Damir Skomina', 'Eslovenia', 14),
('Ovidiu Hațegan', 'Rumanía', 13),
('Danny Makkelie', 'Países Bajos', 10),
('Sandro Ricci', 'Brasil', 10),
('Jorge Larrionda', 'Uruguay', 14),
('Andres Cunha', 'Uruguay', 12),
('Szymon Marciniak', 'Polonia', 11),
('Artur Soares Dias', 'Portugal', 12),
('Benoit Bastien', 'Francia', 10),
('Gianluca Rocchi', 'Italia', 15),
('Michael Oliver', 'Inglaterra', 12),
('Craig Pawson', 'Inglaterra', 10),
('Kevin Friend', 'Inglaterra', 13),
('Anthony Taylor', 'Inglaterra', 11),
('Carlos del Cerro Grande', 'España', 10),
('Pablo González Fuertes', 'España', 10),
('José Luis Munuera Montero', 'España', 11),
('Hernández Hernández', 'España', 10),
('Matej Jug', 'Eslovenia', 10),
('Gábor Bede', 'Hungría', 15),
('Mikael Appelgren', 'Suecia', 10),
('Gustav Svensson', 'Suecia', 9),
('Leif Sundell', 'Suecia', 10),
('Bartosz Frankowski', 'Polonia', 8),
('Radu Petrescu', 'Rumanía', 9),
('Michael Weiner', 'Alemania', 12),
('Krzysztof Jakubik', 'Polonia', 9),
('Aleksandar Stavrev', 'Macedonia', 11),
('Daniel Siebert', 'Alemania', 10),
('Milan Majstorovic', 'Suecia', 8),
('Sergei Karasev', 'Rusia', 12),
('Olegário Benquerença', 'Portugal', 20),
('Viktor Kassai', 'Hungría', 16),
('Howard Webb', 'Inglaterra', 18),
('Javier Estrada Fernández', 'España', 12),
('Mark Geiger', 'Estados Unidos', 15),
('Tamas Bognar', 'Hungría', 10),
('Dámaso Arcediano Monescillo', 'España', 11),
('Alfredo Ingrao', 'Italia', 8),
('Guido Pizarro', 'Argentina', 12),
('Emilio Pérez Pizarro', 'España', 10),
('Felix Brych', 'Alemania', 14),
('Stefan Johannesson', 'Suecia', 10),
('Konstantin Sarsania', 'Rusia', 8),
('Stuart Attwell', 'Inglaterra', 10),
('Michael Jones', 'Inglaterra', 11),
('Ali Al-Badawi', 'Arabia Saudita', 9),
('Abdulrahman Al-Joud', 'Kuwait', 9),
('Zlatko Micić', 'Bosnia y Herzegovina', 10),
('Reza Haghighi', 'Irán', 11),
('Shin-ichi Takada', 'Japón', 10),
('Ryuji Sato', 'Japón', 8),
('Basil Naim', 'Líbano', 9),
('Mohamed Abdallah', 'Egipto', 10),
('Jamal Al-Humaidi', 'Omán', 10),
('David Coote', 'Inglaterra', 8),
('Paul Tierney', 'Inglaterra', 10),
('Mikhail Vilkov', 'Rusia', 10),
('Valentin Kovalenko', 'Rusia', 8),
('Marek Cech', 'República Checa', 9),
('Martin Straka', 'República Checa', 11),
('Vladimir Piskunov', 'Rusia', 9),
('Marius Avram', 'Rumanía', 10),
('Bojan Pandzic', 'Serbia', 8),
('Miro Vucelic', 'Serbia', 8),
('Aleksandar Mijailovic', 'Serbia', 9),
('Marek Szkolnikowski', 'Polonia', 8);


-- Insertar datos en la tabla de torneos
INSERT INTO torneos (nombre, año, tipo) VALUES 
('Champions League', 2024, 'Internacional'), 
('Europa League', 2024, 'Internacional'), 
('Supercopa de Europa', 2024, 'Internacional'), 
('Copa del Mundo', 2022, 'Internacional'), 
('Eurocopa', 2024, 'Internacional'), 
('Copa América', 2024, 'Internacional'), 
('Liga de Naciones de la UEFA', 2024, 'Internacional'), 
('Copa del Rey', 2024, 'Nacional'), 
('FA Cup', 2024, 'Nacional'), 
('Bundesliga', 2024, 'Nacional'), 
('Serie A', 2024, 'Nacional'), 
('Premier League', 2024, 'Nacional'), 
('Eredivisie', 2024, 'Nacional'), 
('Primeira Liga', 2024, 'Nacional'), 
('Ligue 1', 2024, 'Nacional'), 
('MLS Cup', 2024, 'Nacional'), 
('Copa Libertadores', 2024, 'Internacional'), 
('Copa Sudamericana', 2024, 'Internacional'), 
('CONCACAF Champions League', 2024, 'Internacional'), 
('Copa del Mundo Femenina', 2023, 'Internacional'), 
('Eurocopa Femenina', 2025, 'Internacional'), 
('Copa América Femenina', 2022, 'Internacional'), 
('Juegos Olímpicos de Fútbol', 2024, 'Internacional'), 
('Copas Mundiales Sub-20', 2023, 'Internacional'), 
('Copa Mundial Sub-17', 2023, 'Internacional'), 
('Eurocopa Sub-21', 2023, 'Internacional'), 
('Copa Africana de Naciones', 2024, 'Internacional'), 
('Copa Asiática', 2023, 'Internacional'), 
('Copa del Mundo de Clubes', 2025, 'Internacional'), 
('Copa de la Liga', 2024, 'Nacional'), 
('Supercopa de Italia', 2024, 'Nacional'), 
('Supercopa de España', 2024, 'Nacional'), 
('Community Shield', 2024, 'Nacional'), 
('DFB-Pokal', 2024, 'Nacional'), 
('Coppa Italia', 2024, 'Nacional'), 
('Copa do Brasil', 2024, 'Nacional'), 
('MLS All-Star Game', 2024, 'Nacional'), 
('Campeonato Brasileiro', 2024, 'Nacional'), 
('Torneo de Apertura', 2024, 'Nacional'), 
('Torneo de Clausura', 2024, 'Nacional'), 
('Liga MX', 2024, 'Nacional'), 
('Ligue 1 Femenina', 2024, 'Nacional'), 
('FA Women\'s Super League', 2024, 'Nacional'), 
('Liga Femenina de Fútbol', 2024, 'Nacional'), 
('Campeonato de Fútbol Femenino', 2024, 'Nacional'), 
('Copa del Mundo Sub-20', 2023, 'Internacional'), 
('Copa del Mundo Sub-17', 2023,'Nacional');  -- Este es el problema



-- Insertar datos en la tabla de partidos
INSERT INTO partidos (equipo_local_id, equipo_visitante_id, fecha, arbitro_id, torneo_id) VALUES
(1, 2, '2024-09-01', 1, 1),  -- FC Barcelona vs Real Madrid
(3, 4, '2024-09-02', 2, 1),  -- Manchester United vs Bayern Múnich
(5, 6, '2024-09-03', 3, 1),  -- Juventus vs Liverpool
(7, 8, '2024-09-04', 4, 1),  -- PSG vs Inter de Milán
(9, 10, '2024-09-05', 5, 1),  -- AC Milan vs Chelsea
(11, 12, '2024-09-06', 6, 1), -- Borussia Dortmund vs Ajax
(13, 14, '2024-09-07', 7, 1), -- Benfica vs Oporto
(15, 1, '2024-09-08', 8, 1),  -- Sevilla vs FC Barcelona
(2, 3, '2024-09-09', 9, 1),   -- Real Madrid vs Manchester United
(4, 5, '2024-09-10', 10, 1),  -- Bayern Múnich vs Juventus
(6, 7, '2024-09-11', 11, 1),  -- Liverpool vs PSG
(8, 9, '2024-09-12', 12, 1),  -- Inter de Milán vs AC Milan
(10, 11, '2024-09-13', 13, 1), -- Chelsea vs Borussia Dortmund
(12, 13, '2024-09-14', 14, 1), -- Ajax vs Benfica
(14, 15, '2024-09-15', 15, 1), -- Oporto vs Sevilla
(1, 6, '2024-09-16', 16, 1);  -- FC Barcelona vs Liverpool

-- Insertar datos en la tabla de plantillas
INSERT INTO plantillas (jugador_id, equipo_id, torneo_id) VALUES
(1, 1, 1),  -- Lionel Messi en FC Barcelona en Champions League
(2, 2, 1),  -- Cristiano Ronaldo en Real Madrid en Champions League
(3, 3, 1),  -- Marcus Rashford en Manchester United en Champions League
(4, 4, 1),  -- Robert Lewandowski en Bayern Múnich en Champions League
(5, 5, 1),  -- Paulo Dybala en Juventus en Champions League
(6, 6, 1),  -- Mohamed Salah en Liverpool en Champions League
(7, 7, 1),  -- Kylian Mbappé en PSG en Champions League
(8, 7, 1),  -- Neymar en PSG en Champions League
(9, 2, 1),  -- Luka Modrić en Real Madrid en Champions League
(10, 3, 1), -- Kevin De Bruyne en Manchester United en Champions League
(11, 6, 1), -- Virgil van Dijk en Liverpool en Champions League
(12, 4, 1), -- Sadio Mané en Bayern Múnich en Champions League
(13, 3, 1), -- Son Heung-min en Manchester United en Champions League
(14, 9, 1), -- Zlatan Ibrahimović en AC Milan en Champions League
(15, 7, 1); -- Marco Verratti en PSG en Champions League
